udpate setup-catalina-base

diff --git a/setup-catalina-base b/setup-catalina-base
--- a/setup-catalina-base
+++ b/setup-catalina-base
@@ -1,57 +1,131 @@
 #!/bin/bash
-
-SRC_TOMCAT_DIR=$1
-DEST_CATALINA_BASE=$2
-
 usage(){
-  echo "Usage: $0 tomcat_inst_dir dest_catalina_base_dir" 
+    echo "Usage: `basename ${0}` [OPTIONS]... DIRECTORY..."
+    echo -e \
+"
+Make one or more tomcat CATALINA_BASE directory
+
+  DIRECTORY         Destination DIRECTORY(s) for CATALINA_BASE
+
+  -m, --home        Overides CATALINA_HOME enviroment variable. If 
+                    CATALINA_HOME enviroment variable is not set yet, error
+                    arise then exit
+  -u, --user        Set the owner of CATALINA_BASE DIRECTORY. If the bash 
+                    executor is not root, the option will be ignored.
+                    In Some tomcat tarball, files in CATALINA_HOME/conf/ 
+                    is readonly except creator, so su or sudo is needed, 
+                    in the case -u option is used to set owner of DIRECTORY
+                    system path.
+  -t, --test        NOT do anything! display param, location and file for test
+  -h, --help        display this help and exit
+
+EXAMPLE
+    `basename ${0}` -m /opt/tomcat ~/base1
+    `basename ${0}` ~/base1 ~/base2 ~/base3
+    sudo `basename ${0}` ~/base1 -u foo
+"
+    exit 1
 }
 
-if [ ! $# -eq 2 ]; then
-  usage
-  exit 1
+invalidopt(){
+    echo "`basename ${0}`: invalid option ${1:+--'${1}'} ${2:+: ${2}}"
+    echo "Try '`basename ${0}` --help' for more information"
+    exit 1
+}
+
+invalidparam(){
+    echo "`basename ${0}`: invalid parameters ${1:+--'${1}'} ${2:+: ${2}}"
+    echo "Try '`basename ${0}` --help' for more information"
+    exit 1
+}
+
+###################### parse positional parameters
+while [[ $1 ]]; do
+    case $1 in
+        -m | --home )
+            CATALINA_HOME=$2
+            if [[ -z $2 ]]; then
+                invalidopt $1 "must be followed by a path"
+            else
+                shift 2
+            fi
+            ;;
+        -u | --user )
+            DEST_OWNER=$2
+            if [[ -z $2 ]]; then
+                invalidopt $1 "must be followed by a username"
+            else
+                shift 2
+            fi
+            ;;
+        -t | --test )
+            FLAG_TEST=0
+            shift
+            ;;
+        -h | --help )
+            usage
+            break
+            ;;
+        -- ) # End of all options
+            shift
+            break
+            ;;
+        -* ) 
+            invalidopt $1
+            ;;
+        * )
+            DEST_CATALINA_BASES[${#DEST_CATALINA_BASES[@]}]=$1 #put in DEST_CATALINA_BASES array
+            shift
+           ;;
+    esac
+done
+
+############# check CATALINA_HOME
+if [[ -z $CATALINA_HOME ]]; then
+    invalidopt "-m"  "-m CATALINA_HOME need be set, or set in enviroment variable"
 fi
 
-if [ ! -d $SRC_TOMCAT_DIR ]; then
-  echo "$SRC_TOMCAT_DIR is not directory"
-  exit 1
-fi
-    
-if  [ ! -r $SRC_TOMCAT_DIR ]; then
-  echo "$SRC_TOMCAT_DIR can not read"
-  exit 1
+if [[ ${#DEST_CATALINA_BASES[@]} -eq 0 ]]; then
+  invalidparam "" "must set at lease one DIRECTORY"
 fi
 
-if [ ! -d $SRC_TOMCAT_DIR/conf ]; then
-  echo "$SRC_TOMCAT_DIR/conf directory not exists"
-  exit 1
+##################### check whether can not read tomcat conf 
+if [ ! -r $CATALINA_HOME/conf/server.xml ]; then
+  invalidparam "" "conf files can not be read, use sudo or su to root"
 fi
 
-if [ ! -e $DEST_CATALINA_BASE ]; then
-  echo "$DEST_CATALINA_BASE does not exist, create it" 
-  mkdir $DEST_CATALINA_BASE
+#################### check whether root user
+if [[ $(id -nu) -ne 0  ]]; then
+  DEST_OWNER=""            #if not root , ignore -u option
 fi
 
-mkdir $DEST_CATALINA_BASE/conf -p
-if [ ! -r $SRC_TOMCAT_DIR/conf/server.xml ]; then
-  echo "file under $SRC_TOMCAT_DIR/conf can not be read, you should use sudo"
-  sudo cp $SRC_TOMCAT_DIR/conf/* $DEST_CATALINA_BASE/conf
-else
-  cp $SRC_TOMCAT_DIR/conf/* $DEST_CATALINA_BASE/conf
+#################### prepare and display vairable
+echo -e "CATALINA_HOME=\e[1m$CATALINA_HOME\e[0m"
+echo -e "dest base(s)...=\e[1m${DEST_CATALINA_BASES[@]}\e[0m"
+echo -e "DEST_OWNER=\e[1m${DEST_OWNER}\e[0m"
+
+if [[ $FLAG_TEST ]]; then
+    echo -e "\e[1mNOT do anything!\e[0m display param, location and file for test"
+    exit 0
 fi
-sudo chown `id -nu`.`id -ng` $DEST_CATALINA_BASE/conf/*
 
-mkdir $DEST_CATALINA_BASE/bin -p
-touch $DEST_CATALINA_BASE/bin/setenv.sh
+########### copy function
+copyfrom_catalina_home(){
+    DEST_BASE=${1}
+    mkdir $DEST_BASE/conf -p
+    cp $CATALINA_HOME/conf/* $DEST_BASE/conf
+    mkdir $DEST_BASE/bin -p
+    touch $DEST_BASE/bin/setenv.sh
+    mkdir $DEST_BASE/lib -p
+    mkdir $DEST_BASE/logs -p
+    mkdir $DEST_BASE/temp -p
+    mkdir $DEST_BASE/webapps -p
+    mkdir $DEST_BASE/work -p
+}
 
-mkdir $DEST_CATALINA_BASE/lib -p
-
-mkdir $DEST_CATALINA_BASE/logs -p
-
-mkdir $DEST_CATALINA_BASE/temp -p
-
-mkdir $DEST_CATALINA_BASE/webapps -p
-
-mkdir $DEST_CATALINA_BASE/work -p
-
-echo "CATALINA_BASE directory created, next you should set CATALINA_BASE enviroment"
+for i in ${DEST_CATALINA_BASES[@]}; do
+    copyfrom_catalina_home $i
+    if [[ ! -z $DEST_OWNER ]]; then
+      chown ${DEST_OWNER}.$(id -ng ${DEST_OWNER}) $i -R  
+    fi
+done
